### ISSUE TITLE
backend模块在maven仓库

### ISSUE THREAD

**Issue by Killy412** [uncleAndyChen/springBootIntegrationUEditor#1]
backend模块在很多maven仓库中都有,但是不能用,之前我用的别的ueditor的jar包,显示后端配置错误,引用你的模块就可以成功上传图片视频,是不是backend中的版本问题,你这版本在公共maven仓库中有么

**Comment by uncleAndyChen** [comment]
没有传Maven仓库，我的版本也是经过了好多测试验证才搞好的，最关键还是前端和后端的配置要相互配合。

**Comment by uncleAndyChen** [comment]
@Killy412 不好意思，才注意到这个Issues
